COLOR_RULES = {
    "black": ["white", "black", "red", "blue", "yellow", "pink", "grey", "beige", "green", "purple", "orange", "brown", "gold", "silver", "cream", "navy", "burgundy", "charcoal", "olive", "khaki", "mustard", "maroon", "coral", "teal", "mint", "lavender", "peach", "turquoise", "plum", "magenta", "tan", "bronze", "champagne", "ivory", "rose", "emerald", "fuchsia", "camel", "nude", "rust", "cappuccino", "sand", "chocolate", "ochre", "amber", "sepia", "coffee", "biscuit", "mocha", "terracotta", "salmon", "apricot", "amber", "cyan", "indigo"],
    "white": ["black", "white", "blue", "red", "green", "pink", "grey", "beige", "brown", "purple", "orange", "navy", "burgundy", "olive", "khaki", "mustard", "coral", "teal", "mint", "lavender", "peach", "turquoise", "plum", "magenta", "tan", "gold", "silver", "rose", "emerald", "fuchsia", "camel", "rust", "cappuccino", "sand", "chocolate", "ochre", "amber", "cyan", "indigo", "lilac", "mauve", "denim", "sky blue", "baby blue", "baby pink", "powder blue"],
    "off white": ["black", "blue", "red", "green", "pink", "grey", "beige", "brown", "navy", "burgundy", "olive", "khaki", "mustard", "terracotta", "camel", "chocolate"],
    "ivory": ["navy", "burgundy", "emerald", "chocolate", "charcoal", "black", "gold", "rose gold", "olive", "plum"],
    "cream": ["brown", "navy", "burgundy", "olive", "chocolate", "black", "grey", "camel", "rust", "tan"],
    "beige": ["white", "black", "blue", "navy", "red", "burgundy", "green", "olive", "brown", "chocolate", "khaki", "rust", "camel", "terracotta", "cappuccino", "tan"],
    "camel": ["black", "white", "navy", "burgundy", "cream", "denim", "olive", "chocolate", "red"],
    "tan": ["white", "black", "navy", "blue", "burgundy", "cream", "olive", "grey"],
    "sand": ["white", "black", "navy", "olive", "brown", "burgundy", "rust"],
    "biscuit": ["white", "black", "navy", "chocolate", "burgundy", "olive"],
    "grey": ["black", "white", "red", "blue", "pink", "yellow", "burgundy", "navy", "purple", "teal", "mustard", "coral", "lavender", "charcoal", "silver"],
    "light grey": ["black", "navy", "burgundy", "white", "pink", "purple", "teal", "blue"],
    "dark grey": ["white", "pink", "yellow", "red", "light grey", "mustard", "cyan", "baby blue"],
    "charcoal": ["white", "pink", "yellow", "red", "light blue", "burgundy", "gold", "silver"],
    "silver": ["black", "white", "navy", "burgundy", "charcoal", "purple", "royal blue", "emerald"],
    "navy": ["white", "beige", "red", "yellow", "gold", "silver", "pink", "grey", "cream", "mustard", "burgundy", "camel", "coral", "peach", "sky blue"],
    "navy blue": ["white", "beige", "red", "yellow", "pink", "grey", "cream", "mustard", "camel"],
    "blue": ["black", "white", "grey", "beige", "red", "pink", "yellow", "orange", "gold", "silver", "brown"],
    "dark blue": ["white", "beige", "yellow", "mustard", "pink", "red", "gold", "cream"],
    "light blue": ["white", "black", "navy", "beige", "grey", "pink", "brown", "burgundy", "camel"],
    "baby blue": ["white", "grey", "navy", "baby pink", "cream", "beige", "brown"],
    "sky blue": ["white", "beige", "navy", "camel", "brown", "grey", "cream"],
    "powder blue": ["white", "navy", "grey", "cream", "beige", "burgundy"],
    "royal blue": ["white", "black", "silver", "gold", "yellow", "beige", "grey"],
    "denim": ["white", "black", "red", "yellow", "pink", "camel", "burgundy", "olive", "beige", "cream"],
    "cyan": ["black", "white", "grey", "navy", "brown"],
    "teal": ["white", "black", "beige", "gold", "mustard", "coral", "cream", "navy"],
    "turquoise": ["white", "black", "beige", "brown", "coral", "gold", "navy"],
    "indigo": ["white", "beige", "gold", "mustard", "grey", "pink"],
    "red": ["black", "white", "grey", "beige", "navy", "blue", "camel", "cream", "gold", "silver"],
    "dark red": ["white", "black", "beige", "gold", "cream", "navy", "grey"],
    "burgundy": ["white", "black", "beige", "cream", "navy", "grey", "gold", "mustard", "camel", "pink"],
    "maroon": ["white", "black", "beige", "cream", "gold", "grey", "mustard"],
    "wine": ["white", "black", "beige", "cream", "gold", "grey", "navy"],
    "crimson": ["white", "black", "grey", "navy", "gold"],
    "ruby": ["white", "black", "silver", "gold", "navy"],
    "brick red": ["black", "white", "beige", "cream", "navy", "olive"],
    "terracotta": ["white", "beige", "cream", "navy", "olive", "black", "chocolate"],
    "rust": ["white", "black", "navy", "beige", "cream", "olive", "denim"],
    "pink": ["black", "white", "grey", "navy", "blue", "beige", "burgundy", "olive", "charcoal"],
    "baby pink": ["white", "grey", "navy", "baby blue", "cream", "beige"],
    "dusty pink": ["white", "grey", "navy", "burgundy", "beige", "cream", "charcoal"],
    "rose": ["white", "black", "grey", "navy", "beige", "gold"],
    "rose gold": ["white", "black", "navy", "burgundy", "grey", "ivory"],
    "blush": ["white", "navy", "grey", "burgundy", "black", "cream"],
    "fuchsia": ["black", "white", "grey", "navy", "yellow", "silver"],
    "magenta": ["black", "white", "grey", "navy", "silver"],
    "coral": ["white", "navy", "grey", "beige", "black", "teal", "turquoise", "cream"],
    "salmon": ["white", "navy", "grey", "beige", "brown"],
    "peach": ["white", "navy", "grey", "beige", "brown", "cream"],
    "apricot": ["white", "navy", "beige", "brown", "cream"],
    "green": ["black", "white", "beige", "grey", "yellow", "gold", "navy", "cream", "brown"],
    "dark green": ["white", "black", "beige", "gold", "cream", "mustard", "camel"],
    "light green": ["white", "black", "navy", "grey", "beige"],
    "olive": ["white", "black", "beige", "cream", "burgundy", "navy", "mustard", "camel", "pink", "rust"],
    "olive green": ["white", "black", "beige", "cream", "burgundy", "navy", "camel"],
    "khaki": ["white", "black", "navy", "burgundy", "red", "cream", "pink"],
    "mint": ["white", "black", "navy", "grey", "beige", "pink", "coral"],
    "mint green": ["white", "navy", "grey", "beige", "pink"],
    "emerald": ["white", "black", "gold", "beige", "cream", "silver", "navy"],
    "emerald green": ["white", "black", "gold", "beige", "cream"],
    "sage": ["white", "beige", "cream", "navy", "grey", "pink", "burgundy"],
    "sage green": ["white", "beige", "cream", "navy", "grey"],
    "army green": ["white", "black", "beige", "cream", "burgundy", "yellow"],
    "pistachio": ["white", "navy", "beige", "cream", "brown"],
    "lime": ["black", "white", "navy", "grey"],
    "yellow": ["black", "white", "blue", "navy", "grey", "charcoal", "purple", "burgundy"],
    "mustard": ["black", "white", "navy", "burgundy", "grey", "denim", "olive", "brown", "teal"],
    "mustard yellow": ["black", "white", "navy", "burgundy", "grey", "denim"],
    "gold": ["black", "white", "navy", "burgundy", "red", "emerald", "royal blue", "charcoal"],
    "amber": ["black", "white", "navy", "cream", "brown"],
    "orange": ["black", "white", "blue", "navy", "grey", "beige", "brown"],
    "dark orange": ["black", "white", "navy", "cream", "brown"],
    "burnt orange": ["white", "black", "navy", "beige", "cream", "olive", "denim"],
    "purple": ["black", "white", "grey", "yellow", "gold", "silver", "beige", "pink"],
    "dark purple": ["white", "black", "gold", "silver", "beige", "cream"],
    "plum": ["white", "black", "beige", "cream", "gold", "grey", "navy"],
    "violet": ["white", "black", "grey", "yellow", "silver"],
    "lavender": ["white", "black", "grey", "navy", "beige", "dark purple", "cream"],
    "lilac": ["white", "grey", "navy", "beige", "cream", "dark purple"],
    "mauve": ["white", "grey", "navy", "beige", "cream", "burgundy"],
    "brown": ["white", "black", "beige", "cream", "green", "olive", "blue", "light blue", "pink", "gold", "camel", "yellow"],
    "dark brown": ["white", "beige", "cream", "pink", "light blue", "gold", "camel"],
    "light brown": ["white", "black", "navy", "burgundy", "cream", "green"],
    "chocolate": ["white", "beige", "cream", "pink", "baby blue", "camel", "gold"],
    "mocha": ["white", "beige", "cream", "pink", "navy"],
    "coffee": ["white", "beige", "cream", "pink", "gold"],
    "cappuccino": ["white", "navy", "burgundy", "black", "cream"],
    "hazelnut": ["white", "black", "navy", "cream"],
    "copper": ["black", "white", "navy", "cream", "beige"],
    "bronze": ["black", "white", "navy", "cream", "burgundy"],
    "champagne": ["black", "navy", "burgundy", "emerald", "charcoal"]
}
